# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Security Guardrails & Financial Compliance Plugins.

Validates input prompts against injection attacks, enforces financial compliance
disclaimers, and prevents unauthorized execution of high-risk actions.
"""

import re
from typing import Optional
from pydantic import BaseModel

from app.observability.logger import AgentExecutionLogger
from app.observability.tracing import trace_span

logger = AgentExecutionLogger(agent_name="safety_guardrails")

# Common prompt injection patterns and unauthorized system instruction overrides
INJECTION_PATTERNS = [
    re.compile(r"ignore\s+previous\s+instructions", re.IGNORECASE),
    re.compile(r"system\s*:\s*you\s+are\s+now", re.IGNORECASE),
    re.compile(r"jailbreak", re.IGNORECASE),
    re.compile(r"bypass\s+(safety|security|rules)", re.IGNORECASE),
    re.compile(r"reveal\s+(api\s*key|secret|password)", re.IGNORECASE),
]

DISCLAIMER_TEXT = (
    "\n\n---\n**DISCLAIMER**: This report is generated by an automated AI financial research system for "
    "informational and educational purposes only. It does not constitute financial, investment, legal, or tax advice."
)


class GuardrailResult(BaseModel):
    """Result returned by safety validation."""

    is_safe: bool
    risk_category: Optional[str] = None
    sanitized_input: str
    message: Optional[str] = None


class FinancialSafetyGuardrail:
    """Enforces safety guardrails across all agent invocations."""

    @classmethod
    def validate_input(cls, user_prompt: str) -> GuardrailResult:
        """Inspect and sanitize incoming user prompt for injection or malicious intent.

        Args:
            user_prompt: Raw user input text.

        Returns:
            GuardrailResult with safety status.
        """
        with trace_span("guardrails.validate_input"):
            if not user_prompt or not user_prompt.strip():
                return GuardrailResult(
                    is_safe=False,
                    risk_category="EMPTY_INPUT",
                    sanitized_input="",
                    message="Input prompt cannot be empty.",
                )

            for pattern in INJECTION_PATTERNS:
                if pattern.search(user_prompt):
                    logger.logger.warning("prompt_injection_detected", pattern=pattern.pattern)
                    return GuardrailResult(
                        is_safe=False,
                        risk_category="PROMPT_INJECTION",
                        sanitized_input="",
                        message="Request blocked by security guardrails: suspicious prompt override attempt detected.",
                    )

            return GuardrailResult(
                is_safe=True,
                sanitized_input=user_prompt.strip(),
            )

    @classmethod
    def enforce_compliance_disclaimer(cls, report_text: str) -> str:
        """Ensure mandatory SEC financial disclaimer is appended to synthesized reports.

        Args:
            report_text: Generated financial report content.

        Returns:
            Report text with compliance disclaimer attached if missing.
        """
        if "DISCLAIMER" not in report_text.upper():
            return report_text + DISCLAIMER_TEXT
        return report_text
